### ISSUE TITLE
Meeting 1

### ISSUE THREAD

**Issue by okmechak** [SocSIM/SocSIM#1]
### Todos:

- [x] Update documentation according to kwant  
- [x] Podeslac artykol po mozgu.  
- [ ] Earth quake model  
- [ ] Opracowac SoC jaki juz jest i zrobic mala iteracje projektu.  
- [x] skype na poniedzialek

**Comment by okmechak** [comment]
Te same punkty juz sa w obrednych issues #4 i #3
